url: http://www.dronelounge.com
baseurl: /dronelounge/

# Site settings
title: The Drone Lounge
email: dronelounge@gmail.com
description: "Welcome to the Drone Lounge, a low key place where I document a few things about drones - in particular the cool things you can do with ArduPilot."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/auturgyptyltd
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/auturgy

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
